services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=${{backend.RAILWAY_STATIC_URL}}
    domains:
      - budget.night-technologies.com

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=${{MongoDB.DATABASE_URL}}
      - JWT_SECRET=${{JWT_SECRET}}
      - DB_NAME=budget_tracker

  MongoDB:
    image: mongo:latest
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: